### ISSUE TITLE
Postgres lib does not compile with Revenj 1.6.2 because of System.Drawing.Common package downgrade

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#187]
Revenj 1.6.2, Postgres lib compilation error:
```
AppData\Local\Temp\DSLPlatform\Postgres\Postgres.csproj : 
error NU1605: Detected package downgrade: System.Drawing.Common from 5.0.3 to 5.0.2. Reference the package directly from the project to select a different version. 
error NU1605:  xxx.DSL -> Revenj 1.6.2 -> Templater 7.1.0 -> System.Drawing.Common (>= 5.0.3) 
error NU1605:  xxx.DSL -> Revenj 1.6.2 -> System.Drawing.Common (>= 5.0.2)

```
Revenj  NuGet should probably depend on System.Drawing.Common >= 5.0.3 because of the Templater dependency.

Workaround is to add that System.Drawing.Common 5.0.3 NuGet:

![image](https://user-images.githubusercontent.com/11263864/190833845-d192b0df-298e-48b6-a745-d5aa292758fc.png)

**Comment by zapov** [comment]
Tnx. I've bumped the lib. I'm assuming this is a minor thing. Does not require new release?

**Comment by Kobus-Smit** [comment]
Thx. Yes, minor for me because of a workaround.
